//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAPAN
    {
        public int IdKyThi { get; set; }
        public string MaMon { get; set; }
        public string MaDe { get; set; }
        public int CauHoi { get; set; }
        public string DapAn1 { get; set; }
        public Nullable<double> ThangDiem { get; set; }
    
        public virtual KYTHI KYTHI { get; set; }
    }
}
