//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DatabaseContainer : DbContext
    {
        public DatabaseContainer()
            : base("name=DatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAILAM> BAILAMs { get; set; }
        public DbSet<DAPAN> DAPANs { get; set; }
        public DbSet<DIEMTHI> DIEMTHIs { get; set; }
        public DbSet<KHOA> KHOAs { get; set; }
        public DbSet<KT_PHONG> KT_PHONG { get; set; }
        public DbSet<KYTHI> KYTHIs { get; set; }
        public DbSet<LOP> LOPs { get; set; }
        public DbSet<NAMHOC> NAMHOCs { get; set; }
        public DbSet<PHONGTHI> PHONGTHIs { get; set; }
        public DbSet<SINHVIEN> SINHVIENs { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<XEPPHONG> XEPPHONGs { get; set; }
        public DbSet<DangKy> DangKies { get; set; }
        public DbSet<ChuyenMuc> ChuyenMucs { get; set; }
    
        public virtual ObjectResult<sp_MaxSinhVien_Result> sp_MaxSinhVien(Nullable<int> masv)
        {
            var masvParameter = masv.HasValue ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MaxSinhVien_Result>("sp_MaxSinhVien", masvParameter);
        }
    }
}
