//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMTHI
    {
        public int MaSV { get; set; }
        public int IdNamHoc { get; set; }
        public string HocKy { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual NAMHOC NAMHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
