//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_PHONG
    {
        public int IdPhong { get; set; }
        public int IdKyThi { get; set; }
        public Nullable<int> SiSo { get; set; }
    
        public virtual KYTHI KYTHI { get; set; }
        public virtual PHONGTHI PHONGTHI { get; set; }
    }
}
