//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYTHI
    {
        public KYTHI()
        {
            this.BAILAMs = new HashSet<BAILAM>();
            this.DAPANs = new HashSet<DAPAN>();
            this.KT_PHONG = new HashSet<KT_PHONG>();
            this.XEPPHONGs = new HashSet<XEPPHONG>();
        }
    
        public int ID { get; set; }
        public string MaKT { get; set; }
        public string TenKT { get; set; }
        public string NgayThi { get; set; }
        public string TGLamBai { get; set; }
        public string TGBatDau { get; set; }
        public string TGKetThuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<BAILAM> BAILAMs { get; set; }
        public virtual ICollection<DAPAN> DAPANs { get; set; }
        public virtual ICollection<KT_PHONG> KT_PHONG { get; set; }
        public virtual ICollection<XEPPHONG> XEPPHONGs { get; set; }
    }
}
