//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public LOP()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public int ID { get; set; }
        public string MaLop { get; set; }
        public int IdKhoa { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
