//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAMHOC
    {
        public NAMHOC()
        {
            this.DIEMTHIs = new HashSet<DIEMTHI>();
        }
    
        public int ID { get; set; }
        public string NamHoc1 { get; set; }
    
        public virtual ICollection<DIEMTHI> DIEMTHIs { get; set; }
    }
}
