//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGTHI
    {
        public PHONGTHI()
        {
            this.KT_PHONG = new HashSet<KT_PHONG>();
        }
    
        public int ID { get; set; }
        public string TenPhong { get; set; }
        public int SucChua { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<KT_PHONG> KT_PHONG { get; set; }
    }
}
