//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEPPHONG
    {
        public int IdSV { get; set; }
        public int IdKyThi { get; set; }
        public Nullable<int> IdPhong { get; set; }
    
        public virtual KYTHI KYTHI { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
